### ISSUE TITLE
Problem with attributes

### ISSUE THREAD

**Issue by benoffi7** [crysehillmes/PersistentSearchView#10]
I add

```
<org.cryse.widget.persistentsearch.PersistentSearchView
        android:layout_width="match_parent"
        android:id="@+id/searchview"
        android:layout_height="wrap_content"
        android:visibility="gone"
        android:layout_alignParentLeft="true"
        android:layout_alignParentTop="true"
        android:elevation="6dp"
        app:persistentSV_displayMode="menuItem"
        app:persistentSV_searchTextColor="#DE000000"
        app:persistentSV_editTextColor="#DE000000"
        app:persistentSV_editHintText="Search"
        app:persistentSV_editHintTextColor="#61000000"
        app:persistentSV_searchCardElevation="4dp"
        app:persistentSV_customToolbarHeight="56dp"/>
```

to my XML and

`xmlns:app="http://schemas.android.com/apk/res-auto"
`
to my root layout in the same XML

And I get a lot of errors. In my styles.xml I add

```
<declare-styleable name="PersistentSearchView">
        <attr name="persistentSV_searchTextColor" format="color"/>
        <attr name="persistentSV_logoDrawable" format="reference"/>
        <attr name="persistentSV_logoString" format="string"/>
        <attr name="persistentSV_editTextColor" format="color"/>
        <attr name="persistentSV_editHintText" format="string"/>
        <attr name="persistentSV_editHintTextColor" format="color"/>
        <attr name="persistentSV_searchCardElevation" format="dimension"/>
        <attr name="persistentSV_displayMode" format="enum">
            <enum name="menuItem" value="0" />
            <enum name="toolbar" value="1" />
        </attr>
        <attr name="persistentSV_homeButtonColor" format="color"/>
        <attr name="persistentSV_customToolbarHeight" format="dimension"/>
        <attr name="persistentSV_homeButtonMode" format="enum">
            <enum name="arrow" value="0" />
            <enum name="burger" value="1" />
        </attr>
    </declare-styleable>

```

its compile but when I run

```
Caused by: java.lang.NoClassDefFoundError: org.cryse.widget.persistentsearch.R$attr


java.lang.ExceptionInInitializerError
                                                                                 at java.lang.reflect.Constructor.constructNative(Native Method)
                                                                                 at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
                                                                                 at android.view.LayoutInflater.createView(LayoutInflater.java:587)
                                                                                 at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:687)
                                                                                 at android.view.LayoutInflater.rInflate(LayoutInflater.java:746)
                                                                                 at android.view.LayoutInflater.inflate(LayoutInflater.java:489)
                                                                                 at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
                                                                                 at android.view.LayoutInflater.inflate(LayoutInflater.java:352)
                                                                                 at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:280)
                                                                                 at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
                                                                                 at com.coffeeandcookies.niclis.ui.Pedido.CategoriesActivity.onCreate(CategoriesActivity.java:68)
                                                                                 at android.app.Activity.performCreate(Activity.java:5008)
                                                                                 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1079)
                                                                                 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2023)
                                                                                 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2084)
                                                                                 at android.app.ActivityThread.access$600(ActivityThread.java:130)
                                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1195)
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                 at android.os.Looper.loop(Looper.java:137)
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:4745)
                                                                                 at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                 at java.lang.reflect.Method.invoke(Method.java:511)
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
                                                                                 at dalvik.system.NativeStart.main(Native Method)
                                                                              Caused by: java.lang.NoClassDefFoundError: org.cryse.widget.persistentsearch.R$attr
                                                                                 at org.cryse.widget.persistentsearch.PersistentSearchView.<clinit>(PersistentSearchView.java:50)
                                                                                 at java.lang.reflect.Constructor.constructNative(Native Method) 
                                                                                 at java.lang.reflect.Constructor.newInstance(Constructor.java:417) 
                                                                                 at android.view.LayoutInflater.createView(LayoutInflater.java:587) 
                                                                                 at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:687) 
                                                                                 at android.view.LayoutInflater.rInflate(LayoutInflater.java:746) 
                                                                                 at android.view.LayoutInflater.inflate(LayoutInflater.java:489) 
                                                                                 at android.view.LayoutInflater.inflate(LayoutInflater.java:396) 
                                                                                 at android.view.LayoutInflater.inflate(LayoutInflater.java:352) 
                                                                                 at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:280) 
                                                                                 at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
                                                                                 at com.coffeeandcookies.niclis.ui.Pedido.CategoriesActivity.onCreate(CategoriesActivity.java:68) 
                                                                                 at android.app.Activity.performCreate(Activity.java:5008) 
                                                                                 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1079) 
                                                                                 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2023) 
                                                                                 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2084) 
                                                                                 at android.app.ActivityThread.access$600(ActivityThread.java:130) 
                                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1195) 
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                                 at android.os.Looper.loop(Looper.java:137) 
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:4745) 
                                                                                 at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                                 at java.lang.reflect.Method.invoke(Method.java:511) 
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786) 
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553) 
                                                                                 at dalvik.system.NativeStart.main(Native Method) 


```

**Comment by benoffi7** [comment]
If I quit all the atributtes

```
<org.cryse.widget.persistentsearch.PersistentSearchView
        android:layout_width="match_parent"
        android:id="@+id/searchview"
        android:layout_height="wrap_content"
        android:visibility="gone"
        android:layout_alignParentLeft="true"
        android:layout_alignParentTop="true"
        android:elevation="6dp"
      />
```

Same error...

**Comment by Yellu** [comment]
<declare-styleable name="PersistentSearchView">
</declare-styleable>

It should be placed in **# res/values/attrs.xml**
